# Project Information
sonar.projectKey=wanderlust
sonar.projectName=WanderLust
sonar.projectVersion=1.0

# Source Code
sonar.sources=.

# SonarQube Server
sonar.host.url=http://host.docker.internal:9000

# Encoding
sonar.sourceEncoding=UTF-8

# Exclude unnecessary files
sonar.exclusions=reports/**,node_modules/**,.scannerwork/**,coverage/**